### ISSUE TITLE
pct_change()

### ISSUE THREAD

**Issue by mk0417** [QuantEcon/quantecon-notebooks-datascience#8]
[pandas/basics.ipynb](https://github.com/QuantEcon/quantecon-notebooks-datascience/blob/master/pandas/basics.ipynb) applies `pct_change()` without arguments.

Is it better to mention the behavior of `pct_change()` in case there are missing values? The default behavior is padding if there is any missing data. Need to use `pct_change(fill_method=None)` if anyone wants the percentage to be missing.

Below is an example:
```
import pandas as pd
import numpy as np

df = pd.DataFrame({'x': [1, 2, np.nan, 3, 4]})

df

output:
    x
0  1.0
1  2.0
2  NaN
3  3.0
4  4.0


df.pct_change()

output:
          x
0       NaN
1  1.000000
2  0.000000
3  0.500000
4  0.333333

df.pct_change(fill_method=None)

output:
          x
0       NaN
1  1.000000
2       NaN
3       NaN
4  0.333333
```

**Comment by wupeifan** [comment]
That's a valid point. I agree that the default padding is nonsense. We'll update that soon, thanks.

**Comment by wupeifan** [comment]
Actually, we **only** mentioned the function in that particular lecture instead of giving examples. For the usage of the function, the users can check the documentation by themselves, as they should always do.
While I won't change the wordings in that lecture, I'll do a thorough check to see whether we used that line anywhere throughout the datascience lecture series. Thanks again for pointing it out.

**Comment by wupeifan** [comment]
OK, the related files will be updated soon.

**Comment by sglyon** [comment]
Thank you @wupeifan for working on this and @mk0417  for raising the issue.
